image: denoland/deno:1.43.3

default:
  interruptible: true

stages:
  - test

fmt:
  stage: test
  script: deno fmt --check

lint:
  stage: test
  script: deno lint

check:
  stage: test
  script: deno task check

test:
  stage: test
  script: deno task test
  variables:
    DITTO_NSEC: nsec1zyg3zyg3zyg3zyg3zyg3zyg3zyg3zyg3zyg3zyg3zyg3zyg3zygs4rm7hz
  artifacts:
    when: always
    paths:
      - deno-test.xml
    reports:
      junit: deno-test.xml